server:
  port: 9000
  servlet:
    context-path: /client

logging:
  level:
    org.springframework.security: DEBUG

security:
  oauth2:
    client:
      clientId: myclient
      clientSecret: myclientsecret
      grant-type: authorization_code
      access-token-uri: http://localhost:9002/auth-server/oauth/token
      user-authorization-uri: http://localhost:9002/auth-server/oauth/authorize
      scope: read,write,tell-joke
    resource:
      user-info-uri: http://localhost:9002/auth-server/user





      